# Generated by Django 4.2.3 on 2023-12-09 14:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_products_datetime'),
        ('message', '0002_project_list_alter_contact_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_list',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 19, 37, 46, 611962)),
        ),
        migrations.AlterField(
            model_name='project_list',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 19, 37, 46, 611962)),
        ),
    ]
